<?php
/*
* This is URL where the Duo JavaScript file (Duo-Web-v1.min.js) will be
* accessible on the web.
*/
define('UL_DUOSEC_JS_URL', 'host.your_domain.tld/js/Duo-Web-v1.min.js');

/*
* URL to load the jQuery library from.
* If you are already using jQuery not only for DuoSec, set this to the URL of the jQuery
* library the rest of your website is using. Otherwsie, you can leave it at default.
*/
define('UL_DUOSEC_JQUERY_URI', 'http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js');

/*
* This is something uniquely generated by you for your application
* and is not shared with Duo.
*/
define('UL_DUOSEC_AKEY', 'CHANGE ME!!!');

/*
* IKEY, SKEY, and HOST should come from the Duo Security admin dashboard
* on the integrations page.
*/
define('UL_DUOSEC_IKEY', 'CHANGE ME!!!');
define('UL_DUOSEC_SKEY', 'CHANGE ME!!!');
define('UL_DUOSEC_HOST', 'CHANGE ME!!!');

?>